name: Front pipeline

on:
    push:
        branches: [main]


env:
    IMAGE_NAME: kadhem320/front-session7
    BUILD_NUMBER: ${{ github.run_number }}
  

jobs:
    unit-test-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: install dependencies
              run: npm install

            - name: run unit tests
              run: npm run test

    code-quality-test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: install dependencies
              run: npm install

            - name: run unit tests
              run: npm run lint

    Docker-build-and-push-job:
        runs-on: ubuntu-latest
        needs: [code-quality-test,unit-test-job]
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Build Docker image
              run: docker build -t kadhem320/front-session7 .

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                    username: ${{ vars.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Tag image with version number
              run: docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}

            - name: Push image with version number
              run: docker push ${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}

            - name: push image latest
              run: docker push ${{ env.IMAGE_NAME }}:latest
           